exclude: [ _posts/source ]
pygments: true
safe: false
paginate: 6
scholar:
  style: apa
  locale: en
  sort_by: year
  order: descending

  source: ./_biblio
  bibliography: labnotebook.bib
tag_page_layout: tag_page
tag_page_dir: tag
markdown: pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
