gems: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives
  - jekyll-crosspost-to-medium
  - jekyll-pandoc
plugins: [jekyll-paginate, jekyll-pandoc]
exclude: [ _posts/source ]
highlighter: pygments
safe: false
paginate: 6

jekyll-archives:
  enabled: [categories,tags]
  layout: 'tag_page'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

jekyll-crosspost-to-medium:
  enabled: true
  status: draft

scholar:
  style: apa
  sort_by: year
  order: descending
  source: ./biblio
  bibliography: labnotebook.bib
  
tag_page_layout: tag_page
tag_page_dir: tag

markdown: Pandoc
pandoc:
  extensions: 
    - mathjax
    - bibliography: /Users/mark/Research/websites/lnraw/biblio/labnotebook.bib
    

author:
  name: Mark E. Madsen
  givenName: Mark
  familyName: Madsen
  github: mmadsen
url: http://notebook.madsenlab.org
title: Lab Notebook for Mark E. Madsen
name: Lab Notebook for Mark E. Madsen
