gems: [jekyll-paginate, jekyll-feed, jekyll-archives, jekyll-crosspost-to-medium]
exclude: [ _posts/source ]
highlighter: pygments
safe: false
paginate: 6

jekyll-crosspost_to_medium:
  enabled: true | false
  cache: .jekyll-crosspost_to_medium
  status: draft
  license: cc-40-by-nc-sa
  backdate: true 


jekyll-archives:
  enabled: [categories,tags]
  layout: 'tag_page'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


scholar:
  style: apa
  sort_by: year
  order: descending
  source: ./biblio
  bibliography: labnotebook.bib
  
tag_page_layout: tag_page
tag_page_dir: tag

markdown: Pandoc
pandoc:
  extensions: 
    - smart
    - mathjax
    - bibliography: /Users/mark/lnraw/biblio/labnotebook.bib
    

author:
  name: Mark E. Madsen
  givenName: Mark
  familyName: Madsen
  github: mmadsen
url: http://notebook.madsenlab.org
title: Lab Notebook for Mark E. Madsen
name: Lab Notebook for Mark E. Madsen
